#ifndef LIBS_OBC_SCRUBBING_INCLUDE_OBC_SCRUBBING_FWD_HPP_
#define LIBS_OBC_SCRUBBING_INCLUDE_OBC_SCRUBBING_FWD_HPP_

namespace obc
{
    class OBCScrubbing;
}

#endif /* LIBS_OBC_SCRUBBING_INCLUDE_OBC_SCRUBBING_FWD_HPP_ */
