#ifndef LIBS_MISSION_SAIL_INCLUDE_MISSION_SADS_FWD_HPP_
#define LIBS_MISSION_SAIL_INCLUDE_MISSION_SADS_FWD_HPP_

namespace mission
{
    struct IDeploySolarArray;
}

#endif /* LIBS_MISSION_SAIL_INCLUDE_MISSION_SADS_FWD_HPP_ */
