#ifndef LIBS_OBC_MEMORY_INCLUDE_OBC_MEMORY_FWD_HPP_
#define LIBS_OBC_MEMORY_INCLUDE_OBC_MEMORY_FWD_HPP_

namespace obc
{
    class OBCMemory;
}

#endif /* LIBS_OBC_MEMORY_INCLUDE_OBC_MEMORY_FWD_HPP_ */
