#ifndef LIBS_MISSION_SAIL_INCLUDE_MISSION_SAIL_FWD_HPP_
#define LIBS_MISSION_SAIL_INCLUDE_MISSION_SAIL_FWD_HPP_

namespace mission
{
    struct IOpenSail;
}

#endif /* LIBS_MISSION_SAIL_INCLUDE_MISSION_SAIL_FWD_HPP_ */
